<?xml version="1.0" encoding="utf-8"?><Database Name="QUANLYCAFE3" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=QUANLYCAFE3;Integrated Security=True" SettingsObjectName="QUANLYQUANCAFE.Properties.Settings" SettingsPropertyName="QUANLYCAFE3ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BAN" Member="BANs">
    <Type Name="BAN">
      <Column Name="MaBan" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenBan" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="TrangThai" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="MaCN" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="BAN_HOADON" Member="HOADONs" ThisKey="MaBan" OtherKey="MaBan" Type="HOADON" />
      <Association Name="CHINHANH_BAN" Member="CHINHANH" ThisKey="MaCN" OtherKey="MaCN" Type="CHINHANH" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CAFE" Member="CAFEs">
    <Type Name="CAFE">
      <Column Name="MaCF" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenCF" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HinhAnh" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Gia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="CAFE_HOADON" Member="HOADONs" ThisKey="MaCF" OtherKey="MaCF" Type="HOADON" />
    </Type>
  </Table>
  <Table Name="dbo.CALAMVIEC" Member="CALAMVIECs">
    <Type Name="CALAMVIEC">
      <Column Name="MaCLV" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenCLV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GioBD" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="GioKT" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SoTien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="CALAMVIEC_QUANLYNHANVIEN" Member="QUANLYNHANVIENs" ThisKey="MaCLV" OtherKey="MaCLV" Type="QUANLYNHANVIEN" />
    </Type>
  </Table>
  <Table Name="dbo.CHINHANH" Member="CHINHANHs">
    <Type Name="CHINHANH">
      <Column Name="MaCN" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenCN" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="TrangThai" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="CHINHANH_BAN" Member="BANs" ThisKey="MaCN" OtherKey="MaCN" Type="BAN" />
    </Type>
  </Table>
  <Table Name="dbo.HOADON" Member="HOADONs">
    <Type Name="HOADON">
      <Column Name="MaHD" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Ngay" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="TongTien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GiamGia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DiemTL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaBan" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MaKH" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MaNV" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MaCF" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MaCLV" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MaQL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="BAN_HOADON" Member="BAN" ThisKey="MaBan" OtherKey="MaBan" Type="BAN" IsForeignKey="true" />
      <Association Name="CAFE_HOADON" Member="CAFE" ThisKey="MaCF" OtherKey="MaCF" Type="CAFE" IsForeignKey="true" />
      <Association Name="KHACH_HOADON" Member="KHACH" ThisKey="MaKH" OtherKey="MaKH" Type="KHACH" IsForeignKey="true" />
      <Association Name="NHANVIEN_HOADON" Member="NHANVIEN" ThisKey="MaNV" OtherKey="MaNV" Type="NHANVIEN" IsForeignKey="true" />
      <Association Name="QUANLYNHANVIEN_HOADON" Member="QUANLYNHANVIEN" ThisKey="MaQL" OtherKey="MaQL" Type="QUANLYNHANVIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KHACH" Member="KHACHes">
    <Type Name="KHACH">
      <Column Name="MaKH" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenKH" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(13)" CanBeNull="true" />
      <Column Name="DiemTL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="KHACH_HOADON" Member="HOADONs" ThisKey="MaKH" OtherKey="MaKH" Type="HOADON" />
    </Type>
  </Table>
  <Table Name="dbo.NHANVIEN" Member="NHANVIENs">
    <Type Name="NHANVIEN">
      <Column Name="MaNV" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNV" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(13) NOT NULL" CanBeNull="false" />
      <Column Name="ChucVu" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NgayNhanViec" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="[_Admin]" Member="_Admin" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Association Name="NHANVIEN_HOADON" Member="HOADONs" ThisKey="MaNV" OtherKey="MaNV" Type="HOADON" />
      <Association Name="NHANVIEN_QUANLYNHANVIEN" Member="QUANLYNHANVIENs" ThisKey="MaNV" OtherKey="MaNV" Type="QUANLYNHANVIEN" />
    </Type>
  </Table>
  <Table Name="dbo.QUANLYNHANVIEN" Member="QUANLYNHANVIENs">
    <Type Name="QUANLYNHANVIEN">
      <Column Name="MaQL" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaNV" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MaCLV" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="QUANLYNHANVIEN_HOADON" Member="HOADONs" ThisKey="MaQL" OtherKey="MaQL" Type="HOADON" />
      <Association Name="CALAMVIEC_QUANLYNHANVIEN" Member="CALAMVIEC" ThisKey="MaCLV" OtherKey="MaCLV" Type="CALAMVIEC" IsForeignKey="true" />
      <Association Name="NHANVIEN_QUANLYNHANVIEN" Member="NHANVIEN" ThisKey="MaNV" OtherKey="MaNV" Type="NHANVIEN" IsForeignKey="true" />
    </Type>
  </Table>
</Database>